[nfs]
172.31.83.192 ansible_ssh_user='ec2-user'

[webservers]
172.31.94.121 ansible_ssh_user='ec2-user'
172.31.82.160 ansible_ssh_user='ec2-user'

[db]
172.31.89.199 ansible_ssh_user='ubuntu' 

[lb]
172.31.95.146 ansible_ssh_user='ubuntu'

